# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.das-pilot.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.das-pilot.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.das-pilot.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.das-pilot.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.das-pilot.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.das-pilot.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  orderer.das-pilot.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.das-pilot.com
    container_name: orderer.das-pilot.com
    ports:
      - "7050:7050"
    networks:
      - byfn

  peer0.org1.das-pilot.com:
    container_name: peer0.org1.das-pilot.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.das-pilot.com
    ports:
       - "7051:7051"
       - "7053:7053"
    networks:
      - byfn

  peer1.org1.das-pilot.com:
    container_name: peer1.org1.das-pilot.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.das-pilot.com
    networks:
      - byfn

  peer0.org2.das-pilot.com:
    container_name: peer0.org2.das-pilot.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.das-pilot.com
    networks:
      - byfn

  peer1.org2.das-pilot.com:
    container_name: peer1.org2.das-pilot.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.das-pilot.com
    networks:
      - byfn

  cli:
      container_name: cli
      image: hyperledger/fabric-tools
      tty: true
      environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_LOGGING_LEVEL=DEBUG
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=peer0.org1.das-pilot.com:7051
        - CORE_PEER_LOCALMSPID=Org1MSP
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.das-pilot.com/peers/peer0.org1.das-pilot.com/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.das-pilot.com/peers/peer0.org1.das-pilot.com/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.das-pilot.com/peers/peer0.org1.das-pilot.com/tls/ca.crt
        - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.das-pilot.com/users/Admin@org1.das-pilot.com/msp
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep 100000'
      volumes:
          - /var/run/:/host/var/run/
          - ./block-listener/listener:/opt/gopath/src/github.com/hyperledger/fabric/block-listener
          - ./chaincodes:/opt/gopath/src/github.com/hyperledger/fabric/chaincodes
          - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
          - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      depends_on:
        - orderer.das-pilot.com
        - peer0.org1.das-pilot.com
        - peer0.org2.das-pilot.com
      networks:
        - byfn
  das-api:
      container_name: das-api
      image: hyperledger/fabric-tools
      ports:
        - "8000:8000"
      environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_LOGGING_LEVEL=DEBUG
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=peer0.org1.das-pilot.com:7051
        - CORE_PEER_LOCALMSPID=Org1MSP
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.das-pilot.com/peers/peer0.org1.das-pilot.com/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.das-pilot.com/peers/peer0.org1.das-pilot.com/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.das-pilot.com/peers/peer0.org1.das-pilot.com/tls/ca.crt
        - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.das-pilot.com/users/Admin@org1.das-pilot.com/msp
      working_dir: /opt/gopath/src/github.com/das-pilot/das-go
      command: sleep 100000
      volumes:
          - $GOPATH:/opt/gopath/
      networks:
        - byfn